### ISSUE TITLE
🐛 fix: GPT-4o-Mini VLM Model improvement

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [KakaoTech-14-All-in-one-move/AIM-14-AI#16]
# Title

- GPT-4o-Mini VLM Model v1 개선

# TODO

- [x] 프롬프트 줄 때 페르소나 부여
- [x] 4o로 했을때랑 비교
- [x] 프롬프트에 왜 **같은 기호 제거
- [x] 프롬프트 엔지니어링 할때 보통 예시를 맨 아래에 써야 더 잘 나옵니다.(추가 지침을 위로 올리기)

# etc

- 개선 작업 후 모듈화 작업 진행 예정
