### ISSUE TITLE
🐛 fix: Modify log format

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [KakaoTech-14-All-in-one-move/AIM-14-AI#49]
# Title

- Log format 수정 

# TODO

- [x] logging_config.json 수정
- [x] logging_filter.py 수정
- [x] main.py 수정

# etc

- request_id를 BE에서 통신할떄 header에 값을 줘서 그 값을 request_id로 사용한다.
- 참고자료
https://www.notion.so/Modifying-Log-Format-1545deb8ae85807abd80f2d32945331a?pvs=4
