### ISSUE TITLE
✨ feat: VLM Performance Improvement (Object Localization & Prompt)

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [KakaoTech-14-All-in-one-move/AIM-14-AI#61]
# Title

- VLM 피드백 성능개선

# TODO

- [x] VLM Model System instruction 개선
- [x] Prompt.txt 수정
- [x] Object Localization 기능 추가 (Opencv)

# etc

- 한번 VLM 관련 논문들 읽어보면서 Prompt Engineering 방법 공부

**Comment by Daehyun-Bigbread** [comment]
VLM만으로 Object Localization 하는건 성능 이슈가 있어서 취소, Computer Vision을 적용해서 진행예정.
