### ISSUE TITLE
💚 ci/cd: VLM Server Serving

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [KakaoTech-14-All-in-one-move/AIM-14-AI#63]
# Title

- VLM (영상 처리 서버) Serving

# TODO

- [x] VLM (영상 처리 서버) Docker file
- [x] VLM (영상 처리 서버) .dockerignore setting
- [x] Serving Test & 오류 대응

# etc

- Selina가 진행 예정.
